name: Build/Release

on:
  push:
    # Run this workflow when a tag starting with "v" is pushed
    tags:
      - 'v*'
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  release:
    # Run the job on each OS in the matrix
    runs-on: ${{ matrix.os }}
    env:
      # Make sure Electron Builder can publish to GitHub Releases.
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Publish if the ref is a tag (like "v1.0.0"), otherwise do not publish.
      PUBLISH_FLAG: ${{ startsWith(github.ref, 'refs/tags/v') && 'always' || 'never' }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Install libarchive-tools (for Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools

      - name: Build Application
        run: npx electron-builder build --publish $PUBLISH_FLAG
